# AutoFS
    - name: Install Packages
      yum:
        name:
          - autofs
          - nfs-utils
        state: installed

    - name: Start Service
      service:
        name: autofs
        state: started
        enabled: yes

    - name: showmount
      shell: showmount -e 192.168.34.77
          
    - name: mkdir
      file:
        state: directory
        path: /home/users
        mode: '0755'
        owner: root
        group: root

    - name: auto.master
      lineinfile:
        path: /etc/auto.master
        line: "/home/users   /etc/auto.users --timeout 60"
        state: present
  
    - name: auto.users
      lineinfile:
        path: /etc/auto.users
        create: yes
        state: present
        line: "*   -rw,sync 192.168.34.77:/home/users/&"

    - name: Restart Service
      service:
        name: autofs
        state: restarted

