---
- hosts: dnsm
  become: yes
  remote_user: ansible
  tasks:
    - name: Copy file to DNS server
      copy:
        src: /tmp/flz.txt
        dest: /tmp/flz.txt

    - name: Append to zones file
      shell: cat /tmp/flz.txt >> /var/named/ziyotek3.flz

    - name: Copy file to DNS server
      copy:
        src: /tmp/rlz.txt
        dest: /tmp/rlz.txt

    - name: Append to zones file
      shell: cat /tmp/rlz.txt >> /var/named/ziyotek3.rlz

    - name: serial change
      lineinfile:
        path: /var/named/ziyotek3.flz
        regex: 'serial$'
        line: '                                         20200530   ; serial'

    - name: serial change
      lineinfile:
        path: /var/named/ziyotek3.rlz
        regex: 'serial$'
        line: '                                         20200530   ; serial'

    - name: Reload named
      service:
        name: named
        state: reloaded

