# DisableRoot, SELinux, Firewalls, Packages

   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes

   - name: Restart sshd
     service: 
       name: sshd
       state: restarted  

   - name: selinux off
     shell: setenforce 0
   - name: selinux off
     shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
     
   - name: firewall off
     service:
        name: firewalld
#         - iptables
        state: stopped
        enabled: no
     ignore_errors: yes

   - debug:
        msg: '          >>>>>>>>>   HOW    DO   YOU    LIKE    MY    PLAYBOOK ?!  :)    <<<<<<<<<<<<<    '
  

   - name: Extra packages
     yum:
        name: 
          - bind-utils
          - epel-release
          - nfs-utils
          - chrony
          - man
          - man-pages
          - wget
          - openldap-clients
          - nss-pam-ldapd
          - authconfig
          - mlocate
          - sysstat
          - net-tools
        state: present

   - name: Yum Clean
     shell: yum clean all
